# Use `pre-commit autoupdate` to update this

default_language_version:
  python: python3.10
exclude: 'migrations/.*|.*\.(min\.js|svg|json)$'

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: double-quote-string-fixer
      - id: end-of-file-fixer

  - repo: https://github.com/pycqa/isort
    rev: "5.12.0"
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/pycqa/flake8
    rev: "6.0.0"
    hooks:
      - id: flake8

  - repo: https://github.com/psf/black
    rev: "23.3.0"
    hooks:
      - id: black
