## Use `pre-commit autoupdate` to update this
#
#default_language_version:
#  python: python3.10
#exclude: 'migrations/.*|.*\.(min\.js|svg|json)$'
#
#repos:
#  - repo: https://github.com/pre-commit/pre-commit-hooks
#    rev: v4.4.0
#    hooks:
#      - id: double-quote-string-fixer
#      - id: end-of-file-fixer
#
#  - repo: https://github.com/pycqa/isort
#    rev: "5.12.0"
#    hooks:
#      - id: isort
#        args: ["--profile", "black"]
#
#  - repo: https://github.com/pycqa/flake8
#    rev: "6.0.0"
#    hooks:
#      - id: flake8

repos:
- repo: https://github.com/pycqa/flake8
  rev: 3.9.2  # Adjust version if needed
  hooks:
    - id: flake8
      args: ["--config", "setup.cfg"]

- repo: https://github.com/google/yapf
  rev: v0.33.0  # Adjust version if needed
  hooks:
    - id: yapf
      args: ["--config", "setup.cfg"]

- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
    - id: isort
      args: ["--config", "setup.cfg"]
