services:
  api-1:
    container_name: "${APP_NAME}-api-1"
    build:
      context: .
      args:
        - ENVIRONMENT=${ENVIRONMENT}
    image: "botinow-backend-app"
    volumes:
      - .:/app
    command: /app/startup.sh
    ports:
      - "${API_PORT_1}:8000"
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped

  api-2:
    container_name: "${APP_NAME}-api-2"
    build:
      context: .
      args:
        - ENVIRONMENT=${ENVIRONMENT}
    image: "botinow-backend-app"
    volumes:
      - .:/app
    command: /app/startup.sh
    ports:
      - "${API_PORT_2}:8000"
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped

  api-3:
    container_name: "${APP_NAME}-api-3"
    build:
      context: .
      args:
        - ENVIRONMENT=${ENVIRONMENT}
    image: "botinow-backend-app"
    volumes:
      - .:/app
    command: /app/startup.sh
    ports:
      - "${API_PORT_3}:8000"
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped
  db:
    container_name: "${APP_NAME}-database"
    image: postgres:14
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    container_name: "${APP_NAME}-redis"
    restart: unless-stopped
    image: redis:6.2.7
    command: "redis-server /usr/local/etc/redis/redis.conf"
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf

  celery-worker:
    image: "botinow-backend-app"
    build: .
    container_name: "${APP_NAME}-celery-worker"
    command: celery -A app.core.celery.celery worker --loglevel=info
    volumes:
     - .:/app
    depends_on:
      - db
      - api-1
      - api-2
      - api-3
      - redis
    
      

  celery-flower:
    image: "botinow-backend-app"
    build: .
    container_name: "${APP_NAME}-celery-flowe"
    command: celery -A app.core.celery.celery flower --port=5555
    volumes:
     - .:/app
    ports:
      - "5555:5555"
    depends_on:
      - db
      - api-1
      - api-2
      - api-3
      - redis
    

volumes:
  postgres-data:
  redis-data:
