"""remove-user

Revision ID: 01bf29b7856f
Revises: 3279eb357e14
Create Date: 2023-09-07 16:11:31.890445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01bf29b7856f'
down_revision = '3279eb357e14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('shop_categories_user_id_fkey', 'shop_categories', type_='foreignkey')
    op.drop_column('shop_categories', 'user_id')
    op.drop_constraint('shop_products_user_id_fkey', 'shop_products', type_='foreignkey')
    op.drop_column('shop_products', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_products', sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_foreign_key('shop_products_user_id_fkey', 'shop_products', 'users', ['user_id'], ['id'])
    op.add_column('shop_categories', sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_foreign_key('shop_categories_user_id_fkey', 'shop_categories', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
