"""change profile url length

Revision ID: 0435032113a7
Revises: d42179c92ee3
Create Date: 2022-07-25 17:22:10.024009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0435032113a7'
down_revision = 'd42179c92ee3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instagram_pages', sa.Column('instagram_profile_picture_url', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instagram_pages', 'instagram_profile_picture_url')
    # ### end Alembic commands ###
