"""0009_shop_info_required

Revision ID: 06c6596d4af5
Revises: a9ac97a3ec03
Create Date: 2023-12-31 21:23:39.802877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06c6596d4af5'
down_revision = 'a9ac97a3ec03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_shops', sa.Column('is_info_required', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop_shops', 'is_info_required')
    # ### end Alembic commands ###
