"""created at added to content model

Revision ID: 113d236d62bf
Revises: 641e84d700c1
Create Date: 2022-09-03 17:58:23.422546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '113d236d62bf'
down_revision = '641e84d700c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contents', 'created_at')
    # ### end Alembic commands ###
