"""cover image added

Revision ID: 1264dd5a270f
Revises: e618cafb4750
Create Date: 2022-09-20 11:18:57.227801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1264dd5a270f'
down_revision = 'e618cafb4750'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('cover_image', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contents', 'cover_image')
    # ### end Alembic commands ###
