"""0003_add_can_approve

Revision ID: 164729a815eb
Revises: 4299eebab347
Create Date: 2023-11-07 18:04:49.260651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '164729a815eb'
down_revision = '4299eebab347'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('can_approve_payment', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'can_approve_payment')
    # ### end Alembic commands ###
