"""0004_add_can_approve_nullable

Revision ID: 164729a815eb
Revises: a4a1198057a5
Create Date: 2023-11-07 18:29:10.613226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '164729a815eb'
down_revision = 'a4a1198057a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
