"""credit

Revision ID: 2136a1824902
Revises: 69fb8ad8f2e4
Create Date: 2023-04-25 07:54:24.095363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2136a1824902'
down_revision = '69fb8ad8f2e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_plans',
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('extend_days', sa.Integer(), nullable=True),
    sa.Column('extend_count', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('module', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_plans_id'), 'credit_plans', ['id'], unique=False)
    op.create_table('credit_plan_features',
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('plan_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['credit_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_plan_features_id'), 'credit_plan_features', ['id'], unique=False)
    op.create_table('credit_credits',
    sa.Column('module', sa.String(length=20), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_credits_id'), 'credit_credits', ['id'], unique=False)
    op.create_table('credit_invoices',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('payed_at', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('plan_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['credit_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_invoices_id'), 'credit_invoices', ['id'], unique=False)
    op.create_table('credit_credit_logs',
    sa.Column('module', sa.String(length=20), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('days_added', sa.Integer(), nullable=True),
    sa.Column('plan_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('invoice_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['credit_invoices.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['credit_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_credit_logs_id'), 'credit_credit_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_credit_credit_logs_id'), table_name='credit_credit_logs')
    op.drop_table('credit_credit_logs')
    op.drop_index(op.f('ix_credit_invoices_id'), table_name='credit_invoices')
    op.drop_table('credit_invoices')
    op.drop_index(op.f('ix_credit_credits_id'), table_name='credit_credits')
    op.drop_table('credit_credits')
    op.drop_index(op.f('ix_credit_plan_features_id'), table_name='credit_plan_features')
    op.drop_table('credit_plan_features')
    op.drop_index(op.f('ix_credit_plans_id'), table_name='credit_plans')
    op.drop_table('credit_plans')
    # ### end Alembic commands ###
