"""add index

Revision ID: 215453244df4
Revises: a281ea68cbb4
Create Date: 2022-12-11 23:09:48.149629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "215453244df4"
down_revision = "a281ea68cbb4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_instagram_pages_facebook_page_id"),
        "instagram_pages",
        ["facebook_page_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_instagram_pages_instagram_page_id"),
        "instagram_pages",
        ["instagram_page_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_live_chat_messages_from_page_id"),
        "live_chat_messages",
        ["from_page_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_live_chat_messages_to_page_id"),
        "live_chat_messages",
        ["to_page_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_postman_campaigns_facebook_page_id"),
        "postman_campaigns",
        ["facebook_page_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_postman_groups_facebook_page_id"),
        "postman_groups",
        ["facebook_page_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_postman_groups_facebook_page_id"), table_name="postman_groups"
    )
    op.drop_index(
        op.f("ix_postman_campaigns_facebook_page_id"), table_name="postman_campaigns"
    )
    op.drop_index(
        op.f("ix_live_chat_messages_to_page_id"), table_name="live_chat_messages"
    )
    op.drop_index(
        op.f("ix_live_chat_messages_from_page_id"), table_name="live_chat_messages"
    )
    op.drop_index(
        op.f("ix_instagram_pages_instagram_page_id"), table_name="instagram_pages"
    )
    op.drop_index(
        op.f("ix_instagram_pages_facebook_page_id"), table_name="instagram_pages"
    )
    # ### end Alembic commands ###
