"""0007_add_price

Revision ID: 226600bef511
Revises: 2efcdc860266
Create Date: 2023-12-29 21:00:34.383128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '226600bef511'
down_revision = '2efcdc860266'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_shipment_methods', sa.Column('price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop_shipment_methods', 'price')
    # ### end Alembic commands ###
