"""added mid

Revision ID: 226e046c7a62
Revises: f46f949b010d
Create Date: 2022-09-14 10:52:16.922845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '226e046c7a62'
down_revision = 'f46f949b010d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('mid', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'mid')
    # ### end Alembic commands ###
