"""lead_message

Revision ID: 23432815e837
Revises: 40a207bc26e2
Create Date: 2023-10-07 18:57:32.101585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23432815e837'
down_revision = '40a207bc26e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_telegram_lead_messages',
    sa.Column('lead_id', sa.BigInteger(), nullable=True),
    sa.Column('is_lead_to_bot', sa.Boolean(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('mirror_message_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['social_telegram_leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_telegram_lead_messages_id'), 'social_telegram_lead_messages', ['id'], unique=False)
    op.create_index(op.f('ix_social_telegram_lead_messages_message_id'), 'social_telegram_lead_messages', ['message_id'], unique=False)
    op.create_index(op.f('ix_social_telegram_lead_messages_mirror_message_id'), 'social_telegram_lead_messages', ['mirror_message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_social_telegram_lead_messages_mirror_message_id'), table_name='social_telegram_lead_messages')
    op.drop_index(op.f('ix_social_telegram_lead_messages_message_id'), table_name='social_telegram_lead_messages')
    op.drop_index(op.f('ix_social_telegram_lead_messages_id'), table_name='social_telegram_lead_messages')
    op.drop_table('social_telegram_lead_messages')
    # ### end Alembic commands ###
