"""0016_remove_extra_models

Revision ID: 235590fd9073
Revises: 0e50f60e6ab5
Create Date: 2024-03-16 14:33:51.823639

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '235590fd9073'
down_revision = '0e50f60e6ab5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notifier_campaigns_facebook_page_id', table_name='notifier_campaigns')
    op.drop_index('ix_notifier_campaigns_id', table_name='notifier_campaigns')
    op.drop_index('ix_notifier_campaigns_user_id', table_name='notifier_campaigns')
    op.drop_index('ix_databoard_lead_message_stats_facebook_page_id',
                  table_name='databoard_lead_message_stats')
    op.drop_index('ix_databoard_lead_message_stats_id', table_name='databoard_lead_message_stats')

    op.drop_index('ix_live_chat_messages_from_page_id', table_name='live_chat_messages')
    op.drop_index('ix_live_chat_messages_id', table_name='live_chat_messages')
    op.drop_index('ix_live_chat_messages_to_page_id', table_name='live_chat_messages')
    op.drop_index('ix_databoard_live_comment_stats_id', table_name='databoard_live_comment_stats')
    op.drop_index('ix_databoard_comment_stats_facebook_page_id',
                  table_name='databoard_comment_stats')
    op.drop_index('ix_databoard_comment_stats_id', table_name='databoard_comment_stats')
    op.drop_index('ix_bot_builder_chatflows_id', table_name='bot_builder_chatflows')
    op.drop_index('ix_bot_builder_chatflows_user_id', table_name='bot_builder_chatflows')
    op.drop_index('ix_connections_account_id', table_name='connections')
    op.drop_index('ix_connections_id', table_name='connections')
    op.drop_index('ix_connections_user_id', table_name='connections')
    op.drop_index('ix_bot_builder_nodeuies_chatflow_id', table_name='bot_builder_nodeuies')
    op.drop_index('ix_bot_builder_nodeuies_id', table_name='bot_builder_nodeuies')
    op.drop_index('ix_notifier_campaign_leads_campaign_id', table_name='notifier_campaign_leads')
    op.drop_index('ix_notifier_campaign_leads_id', table_name='notifier_campaign_leads')
    op.drop_index('ix_databoard_lead_stats_facebook_page_id', table_name='databoard_lead_stats')
    op.drop_index('ix_databoard_lead_stats_id', table_name='databoard_lead_stats')
    op.drop_index('ix_bot_builder_nodes_chatflow_id', table_name='bot_builder_nodes')
    op.drop_index('ix_bot_builder_nodes_id', table_name='bot_builder_nodes')
    op.drop_index('ix_bot_builder_edges_chatflow_id', table_name='bot_builder_edges')
    op.drop_index('ix_bot_builder_edges_id', table_name='bot_builder_edges')
    op.drop_index('ix_live_chat_leads_facebook_page_id', table_name='live_chat_leads')
    op.drop_index('ix_live_chat_leads_id', table_name='live_chat_leads')
    op.drop_index('ix_live_chat_leads_lead_igs_id', table_name='live_chat_leads')
    op.drop_index('ix_databoard_follower_stats_facebook_page_id',
                  table_name='databoard_follower_stats')
    op.drop_index('ix_databoard_follower_stats_id', table_name='databoard_follower_stats')

    op.drop_table('notifier_campaign_leads')
    op.drop_table('notifier_campaigns')

    op.drop_table('live_chat_messages')
    op.drop_table('live_chat_leads')

    op.drop_table('databoard_lead_message_stats')
    op.drop_table('databoard_live_comment_stats')
    op.drop_table('databoard_comment_stats')
    op.drop_table('databoard_lead_stats')
    op.drop_table('databoard_follower_stats')

    op.drop_table('connections')

    op.drop_table('bot_builder_nodeuies')
    op.drop_table('bot_builder_edges')
    op.drop_table('bot_builder_nodes')
    op.drop_table('bot_builder_chatflows')

    # ### end Alembic commands ###


def downgrade():
    pass
