"""deleted uniq for the slug

Revision ID: 23d25abcbb0c
Revises: 3fb19c5ff74f
Create Date: 2022-09-14 16:59:21.210045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23d25abcbb0c'
down_revision = '3fb19c5ff74f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('contents_slug_key', 'contents', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('contents_slug_key', 'contents', ['slug'])
    # ### end Alembic commands ###
