"""nodeui and edge naming

Revision ID: 24d392fbce40
Revises: 11e1b2ecf94f
Create Date: 2022-09-05 19:41:51.536023

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '24d392fbce40'
down_revision = '11e1b2ecf94f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('edges', sa.Column('from_port', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('edges', sa.Column('to_port', postgresql.UUID(as_uuid=True), nullable=True))
    op.drop_column('edges', 'toPort')
    op.drop_column('edges', 'fromPort')
    op.add_column('nodeuies', sa.Column('has_delete_action', sa.Boolean(), nullable=True))
    op.add_column('nodeuies', sa.Column('has_edit_action', sa.Boolean(), nullable=True))
    op.drop_column('nodeuies', 'hasDeleteAction')
    op.drop_column('nodeuies', 'hasEditAction')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodeuies', sa.Column('hasEditAction', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('nodeuies', sa.Column('hasDeleteAction', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('nodeuies', 'has_edit_action')
    op.drop_column('nodeuies', 'has_delete_action')
    op.add_column('edges', sa.Column('fromPort', postgresql.UUID(), autoincrement=False, nullable=True))
    op.add_column('edges', sa.Column('toPort', postgresql.UUID(), autoincrement=False, nullable=True))
    op.drop_column('edges', 'to_port')
    op.drop_column('edges', 'from_port')
    # ### end Alembic commands ###
