"""0027_chatbot_telegram_bot_cascade

Revision ID: 2d2690165750
Revises: e610dde7d7fe
Create Date: 2024-05-03 14:59:07.929705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d2690165750'
down_revision = 'e610dde7d7fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
