"""0006_drop_price

Revision ID: 2efcdc860266
Revises: e6e174f8a288
Create Date: 2023-12-29 20:59:36.899845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2efcdc860266'
down_revision = 'e6e174f8a288'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop_shipment_methods', 'price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_shipment_methods', sa.Column('price', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
