"""on_delete

Revision ID: 35965afaa6a0
Revises: b97c4f6f663a
Create Date: 2023-10-14 13:36:47.339938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35965afaa6a0'
down_revision = 'b97c4f6f663a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_categories', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('shop_order_items', sa.Column('product_title', sa.String(length=256), nullable=True))
    op.drop_constraint('shop_order_items_product_id_fkey', 'shop_order_items', type_='foreignkey')
    op.create_foreign_key(None, 'shop_order_items', 'shop_products', ['product_id'], ['id'], ondelete='SET NULL')
    op.add_column('shop_payment_methods', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('shop_products', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_constraint('shop_products_shop_id_fkey', 'shop_products', type_='foreignkey')
    op.drop_constraint('shop_products_category_id_fkey', 'shop_products', type_='foreignkey')
    op.create_foreign_key(None, 'shop_products', 'shop_shops', ['shop_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'shop_products', 'shop_categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.add_column('shop_shipment_methods', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop_shipment_methods', 'is_active')
    op.drop_constraint(None, 'shop_products', type_='foreignkey')
    op.drop_constraint(None, 'shop_products', type_='foreignkey')
    op.create_foreign_key('shop_products_category_id_fkey', 'shop_products', 'shop_categories', ['category_id'], ['id'])
    op.create_foreign_key('shop_products_shop_id_fkey', 'shop_products', 'shop_shops', ['shop_id'], ['id'])
    op.drop_column('shop_products', 'is_active')
    op.drop_column('shop_payment_methods', 'is_active')
    op.drop_constraint(None, 'shop_order_items', type_='foreignkey')
    op.create_foreign_key('shop_order_items_product_id_fkey', 'shop_order_items', 'shop_products', ['product_id'], ['id'])
    op.drop_column('shop_order_items', 'product_title')
    op.drop_column('shop_categories', 'is_active')
    # ### end Alembic commands ###
