"""0029_knowledge_base_manual_input

Revision ID: 39898d90520c
Revises: 40c914f67cbc
Create Date: 2024-05-13 14:04:32.555822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39898d90520c'
down_revision = '40c914f67cbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledgebase', sa.Column('manual_input', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledgebase', 'manual_input')
    # ### end Alembic commands ###
