"""0021_is_ai_answer

Revision ID: 3d838d054966
Revises: 4bc2b9dcd3e6
Create Date: 2024-05-18 21:02:48.858661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d838d054966'
down_revision = '4bc2b9dcd3e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_telegram_leads', sa.Column('is_ai_answer', sa.Boolean(), server_default=sa.text('true'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('social_telegram_leads', 'is_ai_answer')
    # ### end Alembic commands ###
