"""0028_knowledge_base_source_link

Revision ID: 40c914f67cbc
Revises: 4db5244a69e5
Create Date: 2024-05-12 19:20:24.962508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40c914f67cbc'
down_revision = '4db5244a69e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chatbot_telegram_bots_telegram_bot_id_fkey', 'chatbot_telegram_bots', type_='foreignkey')
    op.drop_constraint('chatbot_telegram_bots_chatbot_id_fkey', 'chatbot_telegram_bots', type_='foreignkey')
    op.create_foreign_key(None, 'chatbot_telegram_bots', 'chatbots', ['chatbot_id'], ['id'])
    op.create_foreign_key(None, 'chatbot_telegram_bots', 'telegram_bots', ['telegram_bot_id'], ['id'])
    op.add_column('knowledgebase', sa.Column('source_link', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'knowledgebase', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'knowledgebase', type_='unique')
    op.drop_column('knowledgebase', 'source_link')
    op.drop_constraint(None, 'chatbot_telegram_bots', type_='foreignkey')
    op.drop_constraint(None, 'chatbot_telegram_bots', type_='foreignkey')
    op.create_foreign_key('chatbot_telegram_bots_chatbot_id_fkey', 'chatbot_telegram_bots', 'chatbots', ['chatbot_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('chatbot_telegram_bots_telegram_bot_id_fkey', 'chatbot_telegram_bots', 'telegram_bots', ['telegram_bot_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
