"""init2

Revision ID: 4244c3fafb16
Revises: 2731ee39e437
Create Date: 2023-07-17 13:58:24.540583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4244c3fafb16'
down_revision = '2731ee39e437'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('live_chat_contacts', sa.Column('last_interaction_at', sa.DateTime(), nullable=True))
    op.drop_column('live_chat_contacts', 'comment_count')
    op.drop_column('live_chat_contacts', 'message_count')
    op.drop_column('live_chat_contacts', 'live_comment_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('live_chat_contacts', sa.Column('live_comment_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('live_chat_contacts', sa.Column('message_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('live_chat_contacts', sa.Column('comment_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('live_chat_contacts', 'last_interaction_at')
    # ### end Alembic commands ###
