"""changing detail field to data field

Revision ID: 436f7289c48a
Revises: 0e71549a6c84
Create Date: 2022-09-20 06:43:58.713347

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '436f7289c48a'
down_revision = '0e71549a6c84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('data', postgresql.ARRAY(sa.JSON()), nullable=True))
    op.drop_column('contents', 'detail')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('detail', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('contents', 'data')
    # ### end Alembic commands ###
