"""deleting content attachment model

Revision ID: 43b65f3e169b
Revises: a482abb863c4
Create Date: 2022-09-21 12:47:33.412538

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '43b65f3e169b'
down_revision = 'a482abb863c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('content_attachments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_attachments',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('attachment_id', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('content_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('attachment_type', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], name='content_attachments_content_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='content_attachments_pkey')
    )
    # ### end Alembic commands ###
