"""Add IgId to instagram page

Revision ID: 46bf212ca2bf
Revises: 9ef92b70e824
Create Date: 2022-07-24 15:08:22.301356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd42179c92ee3'
down_revision = '9ef92b70e824'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instagram_pages', sa.Column('instagram_page_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instagram_pages', 'instagram_page_id')
    # ### end Alembic commands ###
