"""order-item

Revision ID: 4c67f9f47d98
Revises: d1d3111a48be
Create Date: 2023-09-16 09:48:50.660670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c67f9f47d98'
down_revision = 'd1d3111a48be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_order_items', sa.Column('price', sa.Float(), nullable=True))
    op.add_column('shop_order_items', sa.Column('currency', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop_order_items', 'currency')
    op.drop_column('shop_order_items', 'price')
    # ### end Alembic commands ###
