"""0014_order_amount_analytics

Revision ID: 501051f74878
Revises: 95f145dff250
Create Date: 2024-03-06 16:52:34.631583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '501051f74878'
down_revision = '95f145dff250'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_daily_reports',
    sa.Column('order_count', sa.Float(), nullable=True),
    sa.Column('order_amount', sa.Float(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('shop_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shop_shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_daily_reports_id'), 'shop_daily_reports', ['id'], unique=False)
    op.add_column('shop_orders', sa.Column('total_amount', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop_orders', 'total_amount')
    op.drop_index(op.f('ix_shop_daily_reports_id'), table_name='shop_daily_reports')
    op.drop_table('shop_daily_reports')
    # ### end Alembic commands ###
