"""add-count

Revision ID: 51a223150aef
Revises: 01bf29b7856f
Create Date: 2023-09-08 11:59:54.345705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51a223150aef'
down_revision = '01bf29b7856f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_order_items', sa.Column('count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop_order_items', 'count')
    # ### end Alembic commands ###
