"""added the taskresult model

Revision ID: 5aea4f7e2f5b
Revises: e6e174f8a288
Create Date: 2023-12-19 23:46:18.572134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5aea4f7e2f5b'
down_revision = 'e6e174f8a288'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_results',
    sa.Column('function_name', sa.String(length=255), nullable=True),
    sa.Column('stacktrace', sa.Text(), nullable=True),
    sa.Column('is_successful', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_results_id'), 'task_results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_results_id'), table_name='task_results')
    op.drop_table('task_results')
    # ### end Alembic commands ###
