"""0010_payment_add_fields

Revision ID: 5d40cff9870c
Revises: 7a490ebb8538
Create Date: 2023-10-22 08:00:49.234611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d40cff9870c'
down_revision = '7a490ebb8538'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_orders', sa.Column('payment_information', sa.JSON(), nullable=True))
    op.add_column('shop_shop_payment_methods', sa.Column('information', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop_shop_payment_methods', 'information')
    op.drop_column('shop_orders', 'payment_information')
    # ### end Alembic commands ###
