"""0011_payment_order

Revision ID: 5e280b2ac4b1
Revises: 5d40cff9870c
Create Date: 2023-10-22 08:19:30.504610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e280b2ac4b1'
down_revision = '5d40cff9870c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_orders', sa.Column('shop_payment_method_id', sa.BigInteger(), nullable=True))
    op.drop_constraint('shop_orders_payment_method_id_fkey', 'shop_orders', type_='foreignkey')
    op.create_foreign_key(None, 'shop_orders', 'shop_shop_payment_methods', ['shop_payment_method_id'], ['id'])
    op.drop_column('shop_orders', 'payment_method_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_orders', sa.Column('payment_method_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'shop_orders', type_='foreignkey')
    op.create_foreign_key('shop_orders_payment_method_id_fkey', 'shop_orders', 'shop_payment_methods', ['payment_method_id'], ['id'])
    op.drop_column('shop_orders', 'shop_payment_method_id')
    # ### end Alembic commands ###
