"""0024_add_chatbot_telegram_bot

Revision ID: 5f207eeb606d
Revises: ac973dc6c7ef
Create Date: 2024-04-25 14:01:55.560851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f207eeb606d'
down_revision = 'ac973dc6c7ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatbot_telegram_bots',
                    sa.Column('chatbot_id', sa.BigInteger(), nullable=True),
                    sa.Column('telegram_bot_id', sa.BigInteger(), nullable=True),
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('uuid', sa.UUID(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_chatbot_telegram_bots_id'),
                    'chatbot_telegram_bots', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chatbot_telegram_bots_id'), table_name='chatbot_telegram_bots')
    op.drop_table('chatbot_telegram_bots')
    # ### end Alembic commands ###
