"""shop-telegram

Revision ID: 5fb0bec12705
Revises: 5dde70b22951
Create Date: 2023-09-05 09:35:22.205031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fb0bec12705'
down_revision = '5dde70b22951'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_shops',
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('support_token', sa.String(length=255), nullable=True),
    sa.Column('support_bot_token', sa.String(length=255), nullable=True),
    sa.Column('support_account_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_shops_id'), 'shop_shops', ['id'], unique=False)
    op.create_index(op.f('ix_shop_shops_support_account_chat_id'), 'shop_shops', ['support_account_chat_id'], unique=False)
    op.create_table('telegram_bots',
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('bot_token', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('bot_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_bots_id'), 'telegram_bots', ['id'], unique=False)
    op.create_table('shop_carts',
    sa.Column('shop_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shop_shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_carts_id'), 'shop_carts', ['id'], unique=False)
    op.create_table('shop_categories',
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('shop_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shop_shops.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_categories_id'), 'shop_categories', ['id'], unique=False)
    op.create_table('shop_products',
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('category_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('shop_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['shop_categories.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shop_shops.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_products_id'), 'shop_products', ['id'], unique=False)
    op.create_table('shop_cart_items',
    sa.Column('cart_id', sa.BigInteger(), nullable=True),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['shop_carts.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['shop_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_cart_items_id'), 'shop_cart_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shop_cart_items_id'), table_name='shop_cart_items')
    op.drop_table('shop_cart_items')
    op.drop_index(op.f('ix_shop_products_id'), table_name='shop_products')
    op.drop_table('shop_products')
    op.drop_index(op.f('ix_shop_categories_id'), table_name='shop_categories')
    op.drop_table('shop_categories')
    op.drop_index(op.f('ix_shop_carts_id'), table_name='shop_carts')
    op.drop_table('shop_carts')
    op.drop_index(op.f('ix_telegram_bots_id'), table_name='telegram_bots')
    op.drop_table('telegram_bots')
    op.drop_index(op.f('ix_shop_shops_support_account_chat_id'), table_name='shop_shops')
    op.drop_index(op.f('ix_shop_shops_id'), table_name='shop_shops')
    op.drop_table('shop_shops')
    # ### end Alembic commands ###
