"""added a information json field for the instagram model

Revision ID: 605940aed2e3
Revises: 02a99b978664
Create Date: 2022-09-11 12:10:38.077060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '605940aed2e3'
down_revision = '02a99b978664'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instagram_pages', sa.Column('information', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instagram_pages', 'information')
    # ### end Alembic commands ###
