"""0020_change_credit

Revision ID: 61b9249d6773
Revises: 802b624c0d82
Create Date: 2024-05-16 12:50:10.089543

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '61b9249d6773'
down_revision = '802b624c0d82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatbot_credits',
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatbot_credits_id'), 'chatbot_credits', ['id'], unique=False)
    op.create_index(op.f('ix_chatbot_credits_user_id'), 'chatbot_credits', ['user_id'], unique=False)
    op.drop_index('ix_chatbot_plans_id', table_name='chatbot_plans')
    op.drop_index('ix_purchased_chatbot_plans_id', table_name='purchased_chatbot_plans')
    op.drop_table('purchased_chatbot_plans')
    op.drop_index('ix_chatbot_plan_features_id', table_name='chatbot_plan_features')
    op.drop_table('chatbot_plan_features')
    op.add_column('chatbot_transaction', sa.Column('user_id', sa.BigInteger(), nullable=True))
    op.drop_constraint('chatbot_transaction_chatbot_id_fkey', 'chatbot_transaction', type_='foreignkey')
    op.create_foreign_key(None, 'chatbot_transaction', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('chatbot_transaction', 'title')
    op.drop_column('chatbot_transaction', 'is_extra')
    op.drop_column('chatbot_transaction', 'extend_days')
    op.drop_column('chatbot_transaction', 'extend_chat_count')
    op.drop_column('chatbot_transaction', 'extend_token_count')
    op.drop_column('chatbot_transaction', 'chatbot_id')
    op.drop_table('chatbot_plans')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatbot_plans',
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_extra', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('extend_days', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('extend_chat_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('extend_token_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='chatbot_plans_pkey')
    )
    op.add_column('chatbot_transaction', sa.Column('chatbot_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('chatbot_transaction', sa.Column('extend_token_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('chatbot_transaction', sa.Column('extend_chat_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('chatbot_transaction', sa.Column('extend_days', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('chatbot_transaction', sa.Column('is_extra', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('chatbot_transaction', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'chatbot_transaction', type_='foreignkey')
    op.create_foreign_key('chatbot_transaction_chatbot_id_fkey', 'chatbot_transaction', 'chatbots', ['chatbot_id'], ['id'], ondelete='CASCADE')
    op.drop_column('chatbot_transaction', 'user_id')
    op.create_table('chatbot_plan_features',
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('chatbot_plan_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chatbot_plan_id'], ['chatbot_plans.id'], name='chatbot_plan_features_chatbot_plan_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='chatbot_plan_features_pkey')
    )
    op.create_index('ix_chatbot_plan_features_id', 'chatbot_plan_features', ['id'], unique=False)
    op.create_table('purchased_chatbot_plans',
    sa.Column('from_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('to_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_extra', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('remaining_chat_count', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('remaining_token_count', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('chatbot_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chatbot_id'], ['chatbots.id'], name='purchased_chatbot_plans_chatbot_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='purchased_chatbot_plans_pkey')
    )
    op.create_index('ix_purchased_chatbot_plans_id', 'purchased_chatbot_plans', ['id'], unique=False)
    op.create_index('ix_chatbot_plans_id', 'chatbot_plans', ['id'], unique=False)
    op.drop_index(op.f('ix_chatbot_credits_user_id'), table_name='chatbot_credits')
    op.drop_index(op.f('ix_chatbot_credits_id'), table_name='chatbot_credits')
    op.drop_table('chatbot_credits')
    # ### end Alembic commands ###
