"""add_mid_camp_cont

Revision ID: 69d898a5824d
Revises: 63cef0539480
Create Date: 2022-10-30 06:04:09.890042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69d898a5824d'
down_revision = '63cef0539480'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('postman_campaign_contacts', sa.Column('mid', sa.String(length=255), nullable=True))
    op.add_column('postman_campaigns', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('postman_campaigns', 'created_at')
    op.drop_column('postman_campaign_contacts', 'mid')
    # ### end Alembic commands ###
