"""0010_product_variant_and_shop_table

Revision ID: 6a2d8e3603ed
Revises: f2add10a328e
Create Date: 2024-02-09 18:55:54.001288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a2d8e3603ed'
down_revision = 'f2add10a328e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_tables',
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('shop_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shop_shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_tables_id'), 'shop_tables', ['id'], unique=False)
    op.create_table('shop_product_variants',
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('is_available', sa.Boolean(create_constraint=256), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['shop_products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_product_variants_id'), 'shop_product_variants', ['id'], unique=False)
    op.add_column('shop_order_items', sa.Column('variant_title', sa.String(length=255), nullable=True))
    op.add_column('shop_order_items', sa.Column('product_title', sa.String(length=255), nullable=True))
    op.add_column('shop_orders', sa.Column('table_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'shop_orders', 'shop_tables', ['table_id'], ['id'])
    op.add_column('telegram_bots', sa.Column('welcome_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_bots', 'welcome_message')
    op.drop_constraint(None, 'shop_orders', type_='foreignkey')
    op.drop_column('shop_orders', 'table_id')
    op.drop_column('shop_order_items', 'product_title')
    op.drop_column('shop_order_items', 'variant_title')
    op.drop_index(op.f('ix_shop_product_variants_id'), table_name='shop_product_variants')
    op.drop_table('shop_product_variants')
    op.drop_index(op.f('ix_shop_tables_id'), table_name='shop_tables')
    op.drop_table('shop_tables')
    # ### end Alembic commands ###
