"""0026_knowledge_base_urls

Revision ID: 6a68ec808dbc
Revises: 5f207eeb606d
Create Date: 2024-05-01 13:20:30.998826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a68ec808dbc'
down_revision = '5f207eeb606d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledgebase', sa.Column('urls', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledgebase', 'urls')
    # ### end Alembic commands ###
