"""0012_order_image

Revision ID: 6b19763b6e9a
Revises: 5e280b2ac4b1
Create Date: 2023-10-24 16:33:51.542866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b19763b6e9a'
down_revision = '5e280b2ac4b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_orders', sa.Column('payment_image', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop_orders', 'payment_image')
    # ### end Alembic commands ###
