"""0004_product_fields_update

Revision ID: 6c3d6181e66c
Revises: 164729a815eb
Create Date: 2023-11-08 16:03:28.121304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c3d6181e66c'
down_revision = '164729a815eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop_order_items', 'product_title')
    op.add_column('shop_orders', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('shop_products', sa.Column(
        'is_deleted', sa.Boolean(), nullable=False, default=False))
    op.alter_column('shop_products', 'is_active',
                    existing_type=sa.BOOLEAN(),
                    nullable=False)
    op.alter_column('shop_products', 'is_available',
                    existing_type=sa.BOOLEAN(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shop_products', 'is_available',
                    existing_type=sa.BOOLEAN(),
                    nullable=True)
    op.alter_column('shop_products', 'is_active',
                    existing_type=sa.BOOLEAN(),
                    nullable=True)
    op.drop_column('shop_products', 'is_deleted')
    op.drop_column('shop_orders', 'created_at')
    op.add_column('shop_order_items', sa.Column('product_title',
                  sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
