"""00010_telegram_bot_welcome_msg

Revision ID: 6e9c5bd5b954
Revises: f2add10a328e
Create Date: 2024-02-06 22:36:56.549602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e9c5bd5b954'
down_revision = 'f2add10a328e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_product_variants',
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('is_available', sa.Boolean(create_constraint=256), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['shop_products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_product_variants_id'), 'shop_product_variants', ['id'], unique=False)
    op.add_column('shop_order_items', sa.Column('variant_title', sa.String(length=255), nullable=True))
    op.add_column('shop_order_items', sa.Column('product_title', sa.String(length=255), nullable=True))
    op.add_column('shop_shops', sa.Column('is_info_required', sa.Boolean(), nullable=True))
    op.add_column('telegram_bots', sa.Column('welcome_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_bots', 'welcome_message')
    op.drop_column('shop_shops', 'is_info_required')
    op.drop_column('shop_order_items', 'product_title')
    op.drop_column('shop_order_items', 'variant_title')
    op.drop_index(op.f('ix_shop_product_variants_id'), table_name='shop_product_variants')
    op.drop_table('shop_product_variants')
    # ### end Alembic commands ###
