"""change username and picture

Revision ID: 7f448888e29c
Revises: 9c89f57b6a02
Create Date: 2022-11-01 09:46:06.982287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f448888e29c'
down_revision = '9c89f57b6a02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instagram_pages', sa.Column('username', sa.String(length=255), nullable=True))
    op.add_column('instagram_pages', sa.Column('profile_picture_url', sa.String(length=1024), nullable=True))
    op.drop_column('instagram_pages', 'instagram_profile_picture_url')
    op.drop_column('instagram_pages', 'instagram_username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instagram_pages', sa.Column('instagram_username', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('instagram_pages', sa.Column('instagram_profile_picture_url', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.drop_column('instagram_pages', 'profile_picture_url')
    op.drop_column('instagram_pages', 'username')
    # ### end Alembic commands ###
