"""0019_chatbot_chatbot_credit_and_more

Revision ID: 802b624c0d82
Revises: 68dfcb63db3b
Create Date: 2024-05-14 19:15:23.398093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '802b624c0d82'
down_revision = '68dfcb63db3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatbot_plans',
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_extra', sa.Boolean(), nullable=True),
    sa.Column('extend_days', sa.Integer(), nullable=True),
    sa.Column('extend_chat_count', sa.Integer(), nullable=True),
    sa.Column('extend_token_count', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatbot_plans_id'), 'chatbot_plans', ['id'], unique=False)
    op.create_table('message_builder_messages',
    sa.Column('button_title', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('short_url', sa.String(length=128), nullable=True),
    sa.Column('message_text', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_builder_messages_id'), 'message_builder_messages', ['id'], unique=False)
    op.create_index(op.f('ix_message_builder_messages_short_url'), 'message_builder_messages', ['short_url'], unique=False)
    op.create_index(op.f('ix_message_builder_messages_telegram_chat_id'), 'message_builder_messages', ['telegram_chat_id'], unique=False)
    op.create_table('chatbot_plan_features',
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('chatbot_plan_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['chatbot_plan_id'], ['chatbot_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatbot_plan_features_id'), 'chatbot_plan_features', ['id'], unique=False)
    op.create_table('chatbots',
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatbots_id'), 'chatbots', ['id'], unique=False)
    op.create_table('chatbot_telegram_bots',
    sa.Column('chatbot_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_bot_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['chatbot_id'], ['chatbots.id'], ),
    sa.ForeignKeyConstraint(['telegram_bot_id'], ['telegram_bots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatbot_telegram_bots_id'), 'chatbot_telegram_bots', ['id'], unique=False)
    op.create_table('chatbot_transaction',
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('payed_at', sa.DateTime(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('is_extra', sa.Boolean(), nullable=True),
    sa.Column('extend_days', sa.Integer(), nullable=True),
    sa.Column('extend_chat_count', sa.Integer(), nullable=True),
    sa.Column('extend_token_count', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_authority', sa.String(length=255), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('chatbot_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chatbot_id'], ['chatbots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatbot_transaction_id'), 'chatbot_transaction', ['id'], unique=False)
    op.create_table('knowledgebase',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('metadatas', sa.JSON(), nullable=True),
    sa.Column('manual_input', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=40), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('urls', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('source_link', sa.String(length=255), nullable=True),
    sa.Column('chatbot_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chatbot_id'], ['chatbots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_knowledgebase_id'), 'knowledgebase', ['id'], unique=False)
    op.create_table('purchased_chatbot_plans',
    sa.Column('from_datetime', sa.DateTime(), nullable=True),
    sa.Column('to_datetime', sa.DateTime(), nullable=True),
    sa.Column('is_extra', sa.Boolean(), nullable=True),
    sa.Column('remaining_chat_count', sa.BigInteger(), nullable=True),
    sa.Column('remaining_token_count', sa.BigInteger(), nullable=True),
    sa.Column('chatbot_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['chatbot_id'], ['chatbots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchased_chatbot_plans_id'), 'purchased_chatbot_plans', ['id'], unique=False)
    op.create_table('embedding_costs',
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('total_tokens', sa.BigInteger(), nullable=True),
    sa.Column('knowledgebase_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['knowledgebase_id'], ['knowledgebase.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_embedding_costs_id'), 'embedding_costs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_embedding_costs_id'), table_name='embedding_costs')
    op.drop_table('embedding_costs')
    op.drop_index(op.f('ix_purchased_chatbot_plans_id'), table_name='purchased_chatbot_plans')
    op.drop_table('purchased_chatbot_plans')
    op.drop_index(op.f('ix_knowledgebase_id'), table_name='knowledgebase')
    op.drop_table('knowledgebase')
    op.drop_index(op.f('ix_chatbot_transaction_id'), table_name='chatbot_transaction')
    op.drop_table('chatbot_transaction')
    op.drop_index(op.f('ix_chatbot_telegram_bots_id'), table_name='chatbot_telegram_bots')
    op.drop_table('chatbot_telegram_bots')
    op.drop_index(op.f('ix_chatbots_id'), table_name='chatbots')
    op.drop_table('chatbots')
    op.drop_index(op.f('ix_chatbot_plan_features_id'), table_name='chatbot_plan_features')
    op.drop_table('chatbot_plan_features')
    op.drop_index(op.f('ix_message_builder_messages_telegram_chat_id'), table_name='message_builder_messages')
    op.drop_index(op.f('ix_message_builder_messages_short_url'), table_name='message_builder_messages')
    op.drop_index(op.f('ix_message_builder_messages_id'), table_name='message_builder_messages')
    op.drop_table('message_builder_messages')
    op.drop_index(op.f('ix_chatbot_plans_id'), table_name='chatbot_plans')
    op.drop_table('chatbot_plans')
    # ### end Alembic commands ###
