"""group_name

Revision ID: 8a791f654e9f
Revises: 7f448888e29c
Create Date: 2022-11-05 07:07:30.237929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a791f654e9f'
down_revision = '7f448888e29c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('postman_campaigns', sa.Column('group_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('postman_campaigns', 'group_name')
    # ### end Alembic commands ###
