"""0007_telegram_order

Revision ID: 915f20292a0f
Revises: 96cf4e8cbb70
Create Date: 2023-10-14 17:07:53.645790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '915f20292a0f'
down_revision = '96cf4e8cbb70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_telegram_orders',
    sa.Column('message_reply_to_id', sa.Integer(), nullable=True),
    sa.Column('support_bot_message_id', sa.Integer(), nullable=True),
    sa.Column('bot_message_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['shop_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_telegram_orders_id'), 'shop_telegram_orders', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shop_telegram_orders_id'), table_name='shop_telegram_orders')
    op.drop_table('shop_telegram_orders')
    # ### end Alembic commands ###
