"""shop

Revision ID: 957aff498e69
Revises: 9f1c06c2bd01
Create Date: 2023-08-28 12:52:03.282477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '957aff498e69'
down_revision = '9f1c06c2bd01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_categories',
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_categories_id'), 'shop_categories', ['id'], unique=False)
    op.create_table('shop_products',
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Float(precision=255), nullable=True),
    sa.Column('currency', sa.String(length=32), nullable=True),
    sa.Column('category_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['shop_categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_products_id'), 'shop_products', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shop_products_id'), table_name='shop_products')
    op.drop_table('shop_products')
    op.drop_index(op.f('ix_shop_categories_id'), table_name='shop_categories')
    op.drop_table('shop_categories')
    # ### end Alembic commands ###
