"""0019_chatbot_knowledgebase

Revision ID: 95e240950b26
Revises: 68dfcb63db3b
Create Date: 2024-03-28 00:08:28.323339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95e240950b26'
down_revision = '68dfcb63db3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatbots',
                    sa.Column('name', sa.String(length=255), nullable=True),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('prompt', sa.Text(), nullable=True),
                    sa.Column('user_id', sa.BigInteger(), nullable=True),
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('uuid', sa.UUID(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_chatbots_id'), 'chatbots', ['id'], unique=False)
    op.create_table('knowledgebase',
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('metadatas', sa.JSON(), nullable=True),
                    sa.Column('type', sa.String(length=40), nullable=True),
                    sa.Column('file_path', sa.String(length=255), nullable=True),
                    sa.Column('chatbot_id', sa.BigInteger(), nullable=True),
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('uuid', sa.UUID(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['chatbot_id'], ['chatbots.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_knowledgebase_id'), 'knowledgebase', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledgebase_id'), table_name='knowledgebase')
    op.drop_table('knowledgebase')
    op.drop_index(op.f('ix_chatbots_id'), table_name='chatbots')
    op.drop_table('chatbots')
    # ### end Alembic commands ###
