"""is_available

Revision ID: 96cf4e8cbb70
Revises: 35965afaa6a0
Create Date: 2023-10-14 13:56:18.339497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96cf4e8cbb70'
down_revision = '35965afaa6a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_products', sa.Column('is_available', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop_products', 'is_available')
    # ### end Alembic commands ###
