"""00011_shop_theme

Revision ID: 9b0eb9ae4da9
Revises: 6a2d8e3603ed
Create Date: 2024-02-16 20:34:04.347712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b0eb9ae4da9'
down_revision = '6a2d8e3603ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_tables',
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('shop_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shop_shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_tables_id'), 'shop_tables', ['id'], unique=False)
    op.create_table('shop_themes',
    sa.Column('color_code', sa.String(length=255), nullable=True),
    sa.Column('shop_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shop_shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id')
    )
    op.create_index(op.f('ix_shop_themes_id'), 'shop_themes', ['id'], unique=False)
    op.add_column('shop_orders', sa.Column('table_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'shop_orders', 'shop_tables', ['table_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shop_orders', type_='foreignkey')
    op.drop_column('shop_orders', 'table_id')
    op.drop_index(op.f('ix_shop_themes_id'), table_name='shop_themes')
    op.drop_table('shop_themes')
    op.drop_index(op.f('ix_shop_tables_id'), table_name='shop_tables')
    op.drop_table('shop_tables')
    # ### end Alembic commands ###
