"""telegram

Revision ID: 9f1c06c2bd01
Revises: 5dde70b22951
Create Date: 2023-08-27 17:04:54.404526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f1c06c2bd01'
down_revision = '5dde70b22951'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_bots',
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('app_id', sa.String(length=64), nullable=True),
    sa.Column('app_secret', sa.String(length=128), nullable=True),
    sa.Column('bot_token', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('bot_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_bots_id'), 'telegram_bots', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telegram_bots_id'), table_name='telegram_bots')
    op.drop_table('telegram_bots')
    # ### end Alembic commands ###
