"""0013_shop_telegram_credit_payment

Revision ID: 9fcafa2ccff1
Revises: 6b19763b6e9a
Create Date: 2023-10-29 07:06:09.112719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fcafa2ccff1'
down_revision = '6b19763b6e9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_shop_telegram_payment_records',
    sa.Column('shop_id', sa.BigInteger(), nullable=False),
    sa.Column('plan_id', sa.BigInteger(), nullable=False),
    sa.Column('reply_to_message_id', sa.BigInteger(), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('payment_message_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['credit_plans.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shop_shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_shop_telegram_payment_records_id'), 'credit_shop_telegram_payment_records', ['id'], unique=False)
    op.create_index(op.f('ix_credit_shop_telegram_payment_records_plan_id'), 'credit_shop_telegram_payment_records', ['plan_id'], unique=True)
    op.create_index(op.f('ix_credit_shop_telegram_payment_records_shop_id'), 'credit_shop_telegram_payment_records', ['shop_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_credit_shop_telegram_payment_records_shop_id'), table_name='credit_shop_telegram_payment_records')
    op.drop_index(op.f('ix_credit_shop_telegram_payment_records_plan_id'), table_name='credit_shop_telegram_payment_records')
    op.drop_index(op.f('ix_credit_shop_telegram_payment_records_id'), table_name='credit_shop_telegram_payment_records')
    op.drop_table('credit_shop_telegram_payment_records')
    # ### end Alembic commands ###
