"""changed label name

Revision ID: a281ea68cbb4
Revises: 8a791f654e9f
Create Date: 2022-11-06 11:30:03.173701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a281ea68cbb4'
down_revision = '8a791f654e9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('academy_labels', sa.Column('name', sa.String(length=255), nullable=True))
    op.drop_column('academy_labels', 'label_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('academy_labels', sa.Column('label_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('academy_labels', 'name')
    # ### end Alembic commands ###
