"""added version and time field

Revision ID: a482abb863c4
Revises: f9ae381afaa3
Create Date: 2022-09-21 08:23:33.123570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a482abb863c4'
down_revision = 'f9ae381afaa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('time', sa.String(length=200), nullable=True))
    op.add_column('contents', sa.Column('version', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contents', 'version')
    op.drop_column('contents', 'time')
    # ### end Alembic commands ###
