"""0022_knowledge_base_unique_removal

Revision ID: a7210acf706b
Revises: 3d838d054966
Create Date: 2024-05-19 16:45:37.143106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7210acf706b'
down_revision = '3d838d054966'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('knowledgebase_name_key', 'knowledgebase', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('knowledgebase_name_key', 'knowledgebase', ['name'])
    # ### end Alembic commands ###
