"""0008_payment_info

Revision ID: a9ac97a3ec03
Revises: 226600bef511
Create Date: 2023-12-31 16:24:52.106024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9ac97a3ec03'
down_revision = '226600bef511'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_orders', sa.Column('is_paid', sa.Boolean(), nullable=True))
    op.add_column('shop_orders', sa.Column('paid_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop_orders', 'paid_at')
    op.drop_column('shop_orders', 'is_paid')
    # ### end Alembic commands ###
