"""added models for the postman and the campaign

Revision ID: a9ddce13bad9
Revises: 83d96d9e30e0
Create Date: 2022-10-22 12:55:02.611422

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a9ddce13bad9'
down_revision = '83d96d9e30e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('postman_campaigns',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('page_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('contact_count', sa.Integer(), nullable=True),
    sa.Column('sent_count', sa.Integer(), nullable=True),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('postman_campaign_contacts',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('contact_igsid', sa.String(length=100), nullable=True),
    sa.Column('is_seen', sa.Boolean(), nullable=True),
    sa.Column('reaction', sa.String(length=100), nullable=True),
    sa.Column('contact_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('campaign_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['postman_campaigns.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['live_chat_contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('connections_account_id_application_name_key', 'connections', type_='unique')
    op.add_column('live_chat_contacts', sa.Column('message_count', sa.Integer(), nullable=True))
    op.add_column('live_chat_contacts', sa.Column('comment_count', sa.Integer(), nullable=True))
    op.add_column('live_chat_contacts', sa.Column('live_comment_count', sa.Integer(), nullable=True))
    op.add_column('live_chat_contacts', sa.Column('first_impression', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('live_chat_contacts', 'first_impression')
    op.drop_column('live_chat_contacts', 'live_comment_count')
    op.drop_column('live_chat_contacts', 'comment_count')
    op.drop_column('live_chat_contacts', 'message_count')
    op.create_unique_constraint('connections_account_id_application_name_key', 'connections', ['account_id', 'application_name'])
    op.drop_table('postman_campaign_contacts')
    op.drop_table('postman_campaigns')
    # ### end Alembic commands ###
