"""0022_chatbot_temperature

Revision ID: b08fc6200530
Revises: fa13035bf382
Create Date: 2024-04-21 15:19:55.085577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b08fc6200530'
down_revision = 'fa13035bf382'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatbots', sa.Column('temperature', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chatbots', 'temperature')
    # ### end Alembic commands ###
