"""0025_chatbot_credit

Revision ID: b32388f4dbd9
Revises: 5f207eeb606d
Create Date: 2024-05-01 12:04:51.522495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b32388f4dbd9'
down_revision = '5f207eeb606d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatbot_plans',
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_extra', sa.Boolean(), nullable=True),
    sa.Column('extend_days', sa.Integer(), nullable=True),
    sa.Column('extend_chat_count', sa.Integer(), nullable=True),
    sa.Column('extend_token_count', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatbot_plans_id'), 'chatbot_plans', ['id'], unique=False)
    op.create_table('chatbot_plan_features',
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('chatbot_plan_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['chatbot_plan_id'], ['chatbot_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatbot_plan_features_id'), 'chatbot_plan_features', ['id'], unique=False)
    op.create_table('chatbot_transaction',
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('payed_at', sa.DateTime(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('is_extra', sa.Boolean(), nullable=True),
    sa.Column('extend_days', sa.Integer(), nullable=True),
    sa.Column('extend_chat_count', sa.Integer(), nullable=True),
    sa.Column('extend_token_count', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_authority', sa.String(length=255), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('chatbot_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chatbot_id'], ['chatbots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatbot_transaction_id'), 'chatbot_transaction', ['id'], unique=False)
    op.create_table('purchased_chatbot_plans',
    sa.Column('from_datetime', sa.DateTime(), nullable=True),
    sa.Column('to_datetime', sa.DateTime(), nullable=True),
    sa.Column('is_extra', sa.Boolean(), nullable=True),
    sa.Column('remaining_chat_count', sa.BigInteger(), nullable=True),
    sa.Column('remaining_token_count', sa.BigInteger(), nullable=True),
    sa.Column('chatbot_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['chatbot_id'], ['chatbots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchased_chatbot_plans_id'), 'purchased_chatbot_plans', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchased_chatbot_plans_id'), table_name='purchased_chatbot_plans')
    op.drop_table('purchased_chatbot_plans')
    op.drop_index(op.f('ix_chatbot_transaction_id'), table_name='chatbot_transaction')
    op.drop_table('chatbot_transaction')
    op.drop_index(op.f('ix_chatbot_plan_features_id'), table_name='chatbot_plan_features')
    op.drop_table('chatbot_plan_features')
    op.drop_index(op.f('ix_chatbot_plans_id'), table_name='chatbot_plans')
    op.drop_table('chatbot_plans')
    # ### end Alembic commands ###
