"""0007_lead_number

Revision ID: b97c4f6f663a
Revises: f593e5e89911
Create Date: 2023-10-09 15:51:12.435285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b97c4f6f663a'
down_revision = 'f593e5e89911'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_telegram_leads', sa.Column('lead_number', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_social_telegram_leads_lead_number'), 'social_telegram_leads', ['lead_number'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_social_telegram_leads_lead_number'), table_name='social_telegram_leads')
    op.drop_column('social_telegram_leads', 'lead_number')
    # ### end Alembic commands ###
