"""add text to edge

Revision ID: be189d13b8ac
Revises: 13484331a967
Create Date: 2022-09-10 12:44:24.634078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be189d13b8ac'
down_revision = '13484331a967'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('edges', sa.Column('text', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('edges', 'text')
    # ### end Alembic commands ###
