"""00012_telegram_bot_image

Revision ID: c28de2156d76
Revises: ae1d454cdda5
Create Date: 2024-02-19 17:17:42.869957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c28de2156d76'
down_revision = 'ae1d454cdda5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_bots', sa.Column('button_name', sa.String(length=255), nullable=True))
    op.add_column('telegram_bots', sa.Column('app_link', sa.String(length=255), nullable=True))
    op.add_column('telegram_bots', sa.Column('image', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_bots', 'image')
    op.drop_column('telegram_bots', 'app_link')
    op.drop_column('telegram_bots', 'button_name')
    # ### end Alembic commands ###
