"""campaign_image

Revision ID: c365095115ff
Revises: 884adf77319f
Create Date: 2023-02-24 18:04:48.576574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c365095115ff'
down_revision = '884adf77319f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('postman_campaigns', sa.Column('image', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('postman_campaigns', 'image')
    # ### end Alembic commands ###
