"""order-payment

Revision ID: d1d3111a48be
Revises: 51a223150aef
Create Date: 2023-09-13 10:07:59.567863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1d3111a48be'
down_revision = '51a223150aef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_orders', sa.Column('payment_reference_number', sa.String(length=255), nullable=True))
    op.add_column('shop_orders', sa.Column('payment_card_last_four_number', sa.String(length=16), nullable=True))
    op.add_column('shop_orders', sa.Column('payment_datetime', sa.DateTime(), nullable=True))
    op.add_column('shop_orders', sa.Column('payment_receipt_image', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop_orders', 'payment_receipt_image')
    op.drop_column('shop_orders', 'payment_datetime')
    op.drop_column('shop_orders', 'payment_card_last_four_number')
    op.drop_column('shop_orders', 'payment_reference_number')
    # ### end Alembic commands ###
