"""height fix

Revision ID: d2b018c597f4
Revises: 24d392fbce40
Create Date: 2022-09-05 23:11:53.189660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2b018c597f4'
down_revision = '24d392fbce40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodeuies', sa.Column('height', sa.Integer(), nullable=True))
    op.drop_column('nodeuies', 'heigth')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodeuies', sa.Column('heigth', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('nodeuies', 'height')
    # ### end Alembic commands ###
