"""0016_status_payment

Revision ID: dde3b6e472c2
Revises: faf6692de0c4
Create Date: 2023-10-29 08:03:00.015735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dde3b6e472c2'
down_revision = 'faf6692de0c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_shop_telegram_payment_records', sa.Column('status', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credit_shop_telegram_payment_records', 'status')
    # ### end Alembic commands ###
