"""0001_initial

Revision ID: dde3b6e472c2
Revises: 
Create Date: 2023-10-30 08:00:10.340518

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dde3b6e472c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academy_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['academy_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('academy_labels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credit_plans',
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('extend_days', sa.Integer(), nullable=True),
    sa.Column('extend_count', sa.Integer(), nullable=True),
    sa.Column('original_price', sa.Float(), nullable=False),
    sa.Column('discounted_price', sa.Float(), nullable=False),
    sa.Column('discount_percentage', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('module', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_plans_id'), 'credit_plans', ['id'], unique=False)
    op.create_table('databoard_comment_stats',
    sa.Column('facebook_page_id', sa.BigInteger(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('hour', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('from_datetime', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_databoard_comment_stats_facebook_page_id'), 'databoard_comment_stats', ['facebook_page_id'], unique=False)
    op.create_index(op.f('ix_databoard_comment_stats_id'), 'databoard_comment_stats', ['id'], unique=False)
    op.create_table('databoard_follower_stats',
    sa.Column('facebook_page_id', sa.BigInteger(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('hour', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('from_datetime', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_databoard_follower_stats_facebook_page_id'), 'databoard_follower_stats', ['facebook_page_id'], unique=False)
    op.create_index(op.f('ix_databoard_follower_stats_id'), 'databoard_follower_stats', ['id'], unique=False)
    op.create_table('databoard_lead_message_stats',
    sa.Column('facebook_page_id', sa.BigInteger(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('hour', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('from_datetime', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_databoard_lead_message_stats_facebook_page_id'), 'databoard_lead_message_stats', ['facebook_page_id'], unique=False)
    op.create_index(op.f('ix_databoard_lead_message_stats_id'), 'databoard_lead_message_stats', ['id'], unique=False)
    op.create_table('databoard_lead_stats',
    sa.Column('facebook_page_id', sa.BigInteger(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('hour', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('from_datetime', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_databoard_lead_stats_facebook_page_id'), 'databoard_lead_stats', ['facebook_page_id'], unique=False)
    op.create_index(op.f('ix_databoard_lead_stats_id'), 'databoard_lead_stats', ['id'], unique=False)
    op.create_table('databoard_live_comment_stats',
    sa.Column('facebook_page_id', sa.BigInteger(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('hour', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('from_datetime', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_databoard_live_comment_stats_id'), 'databoard_live_comment_stats', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('persian_name', sa.String(length=100), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_table('shop_payment_methods',
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('information_fields', sa.JSON(), nullable=True),
    sa.Column('payment_fields', sa.JSON(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_payment_methods_id'), 'shop_payment_methods', ['id'], unique=False)
    op.create_table('credit_plan_features',
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('plan_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['credit_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_plan_features_id'), 'credit_plan_features', ['id'], unique=False)
    op.create_table('users',
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=13), nullable=True),
    sa.Column('phone_country_code', sa.String(length=5), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_email_verified', sa.Boolean(), nullable=True),
    sa.Column('profile_image', sa.String(length=255), nullable=True),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_country_code', 'phone_number', name='_phone_number_phone_code_unique_constraint')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('academy_contents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('blocks', postgresql.ARRAY(sa.JSON()), nullable=True),
    sa.Column('slug', sa.String(length=300), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('cover_image', sa.String(length=1024), nullable=True),
    sa.Column('time', sa.String(length=200), nullable=True),
    sa.Column('version', sa.String(length=200), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bot_builder_chatflows',
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_builder_chatflows_id'), 'bot_builder_chatflows', ['id'], unique=False)
    op.create_index(op.f('ix_bot_builder_chatflows_user_id'), 'bot_builder_chatflows', ['user_id'], unique=False)
    op.create_table('connections',
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('application_name', sa.String(length=255), nullable=True),
    sa.Column('account_id', sa.BigInteger(), nullable=True),
    sa.Column('details', sa.ARRAY(sa.JSON()), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connections_account_id'), 'connections', ['account_id'], unique=False)
    op.create_index(op.f('ix_connections_id'), 'connections', ['id'], unique=False)
    op.create_index(op.f('ix_connections_user_id'), 'connections', ['user_id'], unique=False)
    op.create_table('credit_invoices',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('payed_at', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('bought_on_discount', sa.Boolean(), nullable=True),
    sa.Column('plan_name', sa.String(length=255), nullable=True),
    sa.Column('module', sa.String(length=255), nullable=True),
    sa.Column('extend_days', sa.Integer(), nullable=True),
    sa.Column('extend_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_invoices_id'), 'credit_invoices', ['id'], unique=False)
    op.create_table('instagram_pages',
    sa.Column('facebook_user_long_lived_token', sa.String(length=255), nullable=True),
    sa.Column('facebook_user_id', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('facebook_page_id', sa.BigInteger(), nullable=True),
    sa.Column('instagram_page_id', sa.BigInteger(), nullable=True),
    sa.Column('facebook_page_token', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('profile_picture_url', sa.String(length=1024), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('website', sa.String(length=128), nullable=True),
    sa.Column('ig_id', sa.String(length=128), nullable=True),
    sa.Column('followers_count', sa.Integer(), nullable=True),
    sa.Column('follows_count', sa.Integer(), nullable=True),
    sa.Column('biography', sa.Text(), nullable=True),
    sa.Column('leads_count', sa.Integer(), nullable=True),
    sa.Column('comments_count', sa.Integer(), nullable=True),
    sa.Column('live_comment_count', sa.Integer(), nullable=True),
    sa.Column('chats_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instagram_pages_facebook_page_id'), 'instagram_pages', ['facebook_page_id'], unique=False)
    op.create_index(op.f('ix_instagram_pages_id'), 'instagram_pages', ['id'], unique=False)
    op.create_index(op.f('ix_instagram_pages_instagram_page_id'), 'instagram_pages', ['instagram_page_id'], unique=False)
    op.create_table('live_chat_leads',
    sa.Column('lead_igs_id', sa.BigInteger(), nullable=True),
    sa.Column('facebook_page_id', sa.BigInteger(), nullable=True),
    sa.Column('last_message', sa.String(length=1024), nullable=True),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('last_interaction_at', sa.DateTime(), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('profile_image', sa.String(length=1024), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('followers_count', sa.Integer(), nullable=True),
    sa.Column('is_verified_user', sa.Boolean(), nullable=True),
    sa.Column('is_user_follow_business', sa.Boolean(), nullable=True),
    sa.Column('is_business_follow_user', sa.Boolean(), nullable=True),
    sa.Column('first_impression', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_live_chat_leads_facebook_page_id'), 'live_chat_leads', ['facebook_page_id'], unique=False)
    op.create_index(op.f('ix_live_chat_leads_id'), 'live_chat_leads', ['id'], unique=False)
    op.create_index(op.f('ix_live_chat_leads_lead_igs_id'), 'live_chat_leads', ['lead_igs_id'], unique=False)
    op.create_table('live_chat_messages',
    sa.Column('from_page_id', sa.BigInteger(), nullable=True),
    sa.Column('to_page_id', sa.BigInteger(), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('mid', sa.String(length=256), nullable=True),
    sa.Column('send_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_live_chat_messages_from_page_id'), 'live_chat_messages', ['from_page_id'], unique=False)
    op.create_index(op.f('ix_live_chat_messages_id'), 'live_chat_messages', ['id'], unique=False)
    op.create_index(op.f('ix_live_chat_messages_to_page_id'), 'live_chat_messages', ['to_page_id'], unique=False)
    op.create_table('notification_users',
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('notification_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_users_id'), 'notification_users', ['id'], unique=False)
    op.create_table('notifier_campaigns',
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('is_draft', sa.Boolean(), nullable=True),
    sa.Column('facebook_page_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('leads_criteria', sa.JSON(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifier_campaigns_facebook_page_id'), 'notifier_campaigns', ['facebook_page_id'], unique=False)
    op.create_index(op.f('ix_notifier_campaigns_id'), 'notifier_campaigns', ['id'], unique=False)
    op.create_index(op.f('ix_notifier_campaigns_user_id'), 'notifier_campaigns', ['user_id'], unique=False)
    op.create_table('shop_shops',
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_shops_id'), 'shop_shops', ['id'], unique=False)
    op.create_table('telegram_bots',
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('bot_token', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('bot_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_bots_bot_id'), 'telegram_bots', ['bot_id'], unique=False)
    op.create_index(op.f('ix_telegram_bots_id'), 'telegram_bots', ['id'], unique=False)
    op.create_table('academy_content_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['academy_categories.id'], ),
    sa.ForeignKeyConstraint(['content_id'], ['academy_contents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('academy_content_labels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content_id', sa.UUID(), nullable=True),
    sa.Column('label_id', sa.UUID(), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['academy_contents.id'], ),
    sa.ForeignKeyConstraint(['label_id'], ['academy_labels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bot_builder_edges',
    sa.Column('from_id', sa.UUID(), nullable=True),
    sa.Column('to_id', sa.UUID(), nullable=True),
    sa.Column('from_port', sa.UUID(), nullable=True),
    sa.Column('to_port', sa.UUID(), nullable=True),
    sa.Column('from_widget', sa.UUID(), nullable=True),
    sa.Column('text', sa.String(length=255), nullable=True),
    sa.Column('chatflow_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['chatflow_id'], ['bot_builder_chatflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_builder_edges_chatflow_id'), 'bot_builder_edges', ['chatflow_id'], unique=False)
    op.create_index(op.f('ix_bot_builder_edges_id'), 'bot_builder_edges', ['id'], unique=False)
    op.create_table('bot_builder_nodes',
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('chatflow_id', sa.BigInteger(), nullable=True),
    sa.Column('from_widget', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('widget', sa.JSON(), nullable=True),
    sa.Column('quick_replies', postgresql.ARRAY(sa.JSON()), nullable=True),
    sa.Column('is_head', sa.Boolean(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['chatflow_id'], ['bot_builder_chatflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_builder_nodes_chatflow_id'), 'bot_builder_nodes', ['chatflow_id'], unique=False)
    op.create_index(op.f('ix_bot_builder_nodes_id'), 'bot_builder_nodes', ['id'], unique=False)
    op.create_table('bot_builder_nodeuies',
    sa.Column('text', sa.String(length=255), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('ports', postgresql.ARRAY(sa.JSON()), nullable=True),
    sa.Column('has_delete_action', sa.Boolean(), nullable=True),
    sa.Column('has_edit_action', sa.Boolean(), nullable=True),
    sa.Column('chatflow_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['chatflow_id'], ['bot_builder_chatflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_builder_nodeuies_chatflow_id'), 'bot_builder_nodeuies', ['chatflow_id'], unique=False)
    op.create_index(op.f('ix_bot_builder_nodeuies_id'), 'bot_builder_nodeuies', ['id'], unique=False)
    op.create_table('credit_shop_credits',
    sa.Column('shop_id', sa.BigInteger(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shop_shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_shop_credits_id'), 'credit_shop_credits', ['id'], unique=False)
    op.create_index(op.f('ix_credit_shop_credits_shop_id'), 'credit_shop_credits', ['shop_id'], unique=True)
    op.create_table('credit_shop_telegram_payment_records',
    sa.Column('shop_id', sa.BigInteger(), nullable=True),
    sa.Column('plan_id', sa.BigInteger(), nullable=True),
    sa.Column('reply_to_message_id', sa.BigInteger(), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('payment_message_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['credit_plans.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shop_shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_shop_telegram_payment_records_id'), 'credit_shop_telegram_payment_records', ['id'], unique=False)
    op.create_table('notifier_campaign_leads',
    sa.Column('lead_igs_id', sa.BigInteger(), nullable=True),
    sa.Column('is_sent', sa.Boolean(), nullable=True),
    sa.Column('is_seen', sa.Boolean(), nullable=True),
    sa.Column('mid', sa.String(length=255), nullable=True),
    sa.Column('reaction', sa.String(length=100), nullable=True),
    sa.Column('lead_id', sa.BigInteger(), nullable=True),
    sa.Column('campaign_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['notifier_campaigns.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['live_chat_leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifier_campaign_leads_campaign_id'), 'notifier_campaign_leads', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_notifier_campaign_leads_id'), 'notifier_campaign_leads', ['id'], unique=False)
    op.create_table('shop_categories',
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('shop_id', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shop_shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_categories_id'), 'shop_categories', ['id'], unique=False)
    op.create_table('shop_shipment_methods',
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('price', sa.String(length=255), nullable=True),
    sa.Column('currency', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('shop_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shop_shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_shipment_methods_id'), 'shop_shipment_methods', ['id'], unique=False)
    op.create_table('shop_shop_payment_methods',
    sa.Column('shop_id', sa.BigInteger(), nullable=True),
    sa.Column('payment_method_id', sa.BigInteger(), nullable=True),
    sa.Column('information', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['payment_method_id'], ['shop_payment_methods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shop_id'], ['shop_shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_shop_payment_methods_id'), 'shop_shop_payment_methods', ['id'], unique=False)
    op.create_table('shop_shop_telegram_bots',
    sa.Column('support_token', sa.String(length=255), nullable=True),
    sa.Column('support_bot_token', sa.String(length=255), nullable=True),
    sa.Column('support_account_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('is_support_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('shop_id', sa.BigInteger(), nullable=True),
    sa.Column('telegram_bot_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shop_shops.id'], ),
    sa.ForeignKeyConstraint(['telegram_bot_id'], ['telegram_bots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_shop_telegram_bots_id'), 'shop_shop_telegram_bots', ['id'], unique=False)
    op.create_index(op.f('ix_shop_shop_telegram_bots_support_account_chat_id'), 'shop_shop_telegram_bots', ['support_account_chat_id'], unique=False)
    op.create_table('social_telegram_leads',
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('telegram_bot_id', sa.BigInteger(), nullable=True),
    sa.Column('lead_number', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['telegram_bot_id'], ['telegram_bots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_telegram_leads_chat_id'), 'social_telegram_leads', ['chat_id'], unique=False)
    op.create_index(op.f('ix_social_telegram_leads_id'), 'social_telegram_leads', ['id'], unique=False)
    op.create_index(op.f('ix_social_telegram_leads_lead_number'), 'social_telegram_leads', ['lead_number'], unique=False)
    op.create_table('shop_orders',
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('postal_code', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('order_number', sa.Integer(), nullable=True),
    sa.Column('lead_id', sa.BigInteger(), nullable=True),
    sa.Column('shop_id', sa.BigInteger(), nullable=True),
    sa.Column('shipment_method_id', sa.BigInteger(), nullable=True),
    sa.Column('shop_payment_method_id', sa.BigInteger(), nullable=True),
    sa.Column('payment_information', sa.JSON(), nullable=True),
    sa.Column('payment_image', sa.String(length=255), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['social_telegram_leads.id'], ),
    sa.ForeignKeyConstraint(['shipment_method_id'], ['shop_shipment_methods.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shop_shops.id'], ),
    sa.ForeignKeyConstraint(['shop_payment_method_id'], ['shop_shop_payment_methods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_orders_id'), 'shop_orders', ['id'], unique=False)
    op.create_index(op.f('ix_shop_orders_order_number'), 'shop_orders', ['order_number'], unique=False)
    op.create_table('shop_products',
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('category_id', sa.BigInteger(), nullable=True),
    sa.Column('shop_id', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['shop_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shop_id'], ['shop_shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_products_id'), 'shop_products', ['id'], unique=False)
    op.create_table('social_telegram_lead_messages',
    sa.Column('lead_id', sa.BigInteger(), nullable=True),
    sa.Column('is_lead_to_bot', sa.Boolean(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('mirror_message_id', sa.BigInteger(), nullable=True),
    sa.Column('reply_to_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['social_telegram_leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_telegram_lead_messages_id'), 'social_telegram_lead_messages', ['id'], unique=False)
    op.create_index(op.f('ix_social_telegram_lead_messages_message_id'), 'social_telegram_lead_messages', ['message_id'], unique=False)
    op.create_index(op.f('ix_social_telegram_lead_messages_mirror_message_id'), 'social_telegram_lead_messages', ['mirror_message_id'], unique=False)
    op.create_index(op.f('ix_social_telegram_lead_messages_reply_to_id'), 'social_telegram_lead_messages', ['reply_to_id'], unique=False)
    op.create_table('shop_order_items',
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=32), nullable=True),
    sa.Column('product_title', sa.String(length=256), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['shop_orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['shop_products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_order_items_id'), 'shop_order_items', ['id'], unique=False)
    op.create_table('shop_telegram_orders',
    sa.Column('message_reply_to_id', sa.Integer(), nullable=True),
    sa.Column('support_bot_message_id', sa.Integer(), nullable=True),
    sa.Column('bot_message_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['shop_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_telegram_orders_id'), 'shop_telegram_orders', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shop_telegram_orders_id'), table_name='shop_telegram_orders')
    op.drop_table('shop_telegram_orders')
    op.drop_index(op.f('ix_shop_order_items_id'), table_name='shop_order_items')
    op.drop_table('shop_order_items')
    op.drop_index(op.f('ix_social_telegram_lead_messages_reply_to_id'), table_name='social_telegram_lead_messages')
    op.drop_index(op.f('ix_social_telegram_lead_messages_mirror_message_id'), table_name='social_telegram_lead_messages')
    op.drop_index(op.f('ix_social_telegram_lead_messages_message_id'), table_name='social_telegram_lead_messages')
    op.drop_index(op.f('ix_social_telegram_lead_messages_id'), table_name='social_telegram_lead_messages')
    op.drop_table('social_telegram_lead_messages')
    op.drop_index(op.f('ix_shop_products_id'), table_name='shop_products')
    op.drop_table('shop_products')
    op.drop_index(op.f('ix_shop_orders_order_number'), table_name='shop_orders')
    op.drop_index(op.f('ix_shop_orders_id'), table_name='shop_orders')
    op.drop_table('shop_orders')
    op.drop_index(op.f('ix_social_telegram_leads_lead_number'), table_name='social_telegram_leads')
    op.drop_index(op.f('ix_social_telegram_leads_id'), table_name='social_telegram_leads')
    op.drop_index(op.f('ix_social_telegram_leads_chat_id'), table_name='social_telegram_leads')
    op.drop_table('social_telegram_leads')
    op.drop_index(op.f('ix_shop_shop_telegram_bots_support_account_chat_id'), table_name='shop_shop_telegram_bots')
    op.drop_index(op.f('ix_shop_shop_telegram_bots_id'), table_name='shop_shop_telegram_bots')
    op.drop_table('shop_shop_telegram_bots')
    op.drop_index(op.f('ix_shop_shop_payment_methods_id'), table_name='shop_shop_payment_methods')
    op.drop_table('shop_shop_payment_methods')
    op.drop_index(op.f('ix_shop_shipment_methods_id'), table_name='shop_shipment_methods')
    op.drop_table('shop_shipment_methods')
    op.drop_index(op.f('ix_shop_categories_id'), table_name='shop_categories')
    op.drop_table('shop_categories')
    op.drop_index(op.f('ix_notifier_campaign_leads_id'), table_name='notifier_campaign_leads')
    op.drop_index(op.f('ix_notifier_campaign_leads_campaign_id'), table_name='notifier_campaign_leads')
    op.drop_table('notifier_campaign_leads')
    op.drop_index(op.f('ix_credit_shop_telegram_payment_records_id'), table_name='credit_shop_telegram_payment_records')
    op.drop_table('credit_shop_telegram_payment_records')
    op.drop_index(op.f('ix_credit_shop_credits_shop_id'), table_name='credit_shop_credits')
    op.drop_index(op.f('ix_credit_shop_credits_id'), table_name='credit_shop_credits')
    op.drop_table('credit_shop_credits')
    op.drop_index(op.f('ix_bot_builder_nodeuies_id'), table_name='bot_builder_nodeuies')
    op.drop_index(op.f('ix_bot_builder_nodeuies_chatflow_id'), table_name='bot_builder_nodeuies')
    op.drop_table('bot_builder_nodeuies')
    op.drop_index(op.f('ix_bot_builder_nodes_id'), table_name='bot_builder_nodes')
    op.drop_index(op.f('ix_bot_builder_nodes_chatflow_id'), table_name='bot_builder_nodes')
    op.drop_table('bot_builder_nodes')
    op.drop_index(op.f('ix_bot_builder_edges_id'), table_name='bot_builder_edges')
    op.drop_index(op.f('ix_bot_builder_edges_chatflow_id'), table_name='bot_builder_edges')
    op.drop_table('bot_builder_edges')
    op.drop_table('academy_content_labels')
    op.drop_table('academy_content_categories')
    op.drop_index(op.f('ix_telegram_bots_id'), table_name='telegram_bots')
    op.drop_index(op.f('ix_telegram_bots_bot_id'), table_name='telegram_bots')
    op.drop_table('telegram_bots')
    op.drop_index(op.f('ix_shop_shops_id'), table_name='shop_shops')
    op.drop_table('shop_shops')
    op.drop_index(op.f('ix_notifier_campaigns_user_id'), table_name='notifier_campaigns')
    op.drop_index(op.f('ix_notifier_campaigns_id'), table_name='notifier_campaigns')
    op.drop_index(op.f('ix_notifier_campaigns_facebook_page_id'), table_name='notifier_campaigns')
    op.drop_table('notifier_campaigns')
    op.drop_index(op.f('ix_notification_users_id'), table_name='notification_users')
    op.drop_table('notification_users')
    op.drop_index(op.f('ix_live_chat_messages_to_page_id'), table_name='live_chat_messages')
    op.drop_index(op.f('ix_live_chat_messages_id'), table_name='live_chat_messages')
    op.drop_index(op.f('ix_live_chat_messages_from_page_id'), table_name='live_chat_messages')
    op.drop_table('live_chat_messages')
    op.drop_index(op.f('ix_live_chat_leads_lead_igs_id'), table_name='live_chat_leads')
    op.drop_index(op.f('ix_live_chat_leads_id'), table_name='live_chat_leads')
    op.drop_index(op.f('ix_live_chat_leads_facebook_page_id'), table_name='live_chat_leads')
    op.drop_table('live_chat_leads')
    op.drop_index(op.f('ix_instagram_pages_instagram_page_id'), table_name='instagram_pages')
    op.drop_index(op.f('ix_instagram_pages_id'), table_name='instagram_pages')
    op.drop_index(op.f('ix_instagram_pages_facebook_page_id'), table_name='instagram_pages')
    op.drop_table('instagram_pages')
    op.drop_index(op.f('ix_credit_invoices_id'), table_name='credit_invoices')
    op.drop_table('credit_invoices')
    op.drop_index(op.f('ix_connections_user_id'), table_name='connections')
    op.drop_index(op.f('ix_connections_id'), table_name='connections')
    op.drop_index(op.f('ix_connections_account_id'), table_name='connections')
    op.drop_table('connections')
    op.drop_index(op.f('ix_bot_builder_chatflows_user_id'), table_name='bot_builder_chatflows')
    op.drop_index(op.f('ix_bot_builder_chatflows_id'), table_name='bot_builder_chatflows')
    op.drop_table('bot_builder_chatflows')
    op.drop_table('academy_contents')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_credit_plan_features_id'), table_name='credit_plan_features')
    op.drop_table('credit_plan_features')
    op.drop_index(op.f('ix_shop_payment_methods_id'), table_name='shop_payment_methods')
    op.drop_table('shop_payment_methods')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_databoard_live_comment_stats_id'), table_name='databoard_live_comment_stats')
    op.drop_table('databoard_live_comment_stats')
    op.drop_index(op.f('ix_databoard_lead_stats_id'), table_name='databoard_lead_stats')
    op.drop_index(op.f('ix_databoard_lead_stats_facebook_page_id'), table_name='databoard_lead_stats')
    op.drop_table('databoard_lead_stats')
    op.drop_index(op.f('ix_databoard_lead_message_stats_id'), table_name='databoard_lead_message_stats')
    op.drop_index(op.f('ix_databoard_lead_message_stats_facebook_page_id'), table_name='databoard_lead_message_stats')
    op.drop_table('databoard_lead_message_stats')
    op.drop_index(op.f('ix_databoard_follower_stats_id'), table_name='databoard_follower_stats')
    op.drop_index(op.f('ix_databoard_follower_stats_facebook_page_id'), table_name='databoard_follower_stats')
    op.drop_table('databoard_follower_stats')
    op.drop_index(op.f('ix_databoard_comment_stats_id'), table_name='databoard_comment_stats')
    op.drop_index(op.f('ix_databoard_comment_stats_facebook_page_id'), table_name='databoard_comment_stats')
    op.drop_table('databoard_comment_stats')
    op.drop_index(op.f('ix_credit_plans_id'), table_name='credit_plans')
    op.drop_table('credit_plans')
    op.drop_table('academy_labels')
    op.drop_table('academy_categories')
    # ### end Alembic commands ###
