"""0026_knowledge_base_urls

Revision ID: e610dde7d7fe
Revises: b32388f4dbd9
Create Date: 2024-05-01 15:03:49.655487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e610dde7d7fe'
down_revision = 'b32388f4dbd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledgebase', sa.Column('urls', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledgebase', 'urls')
    # ### end Alembic commands ###
