"""change data field name

Revision ID: e618cafb4750
Revises: 436f7289c48a
Create Date: 2022-09-20 06:49:50.984321

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e618cafb4750'
down_revision = '436f7289c48a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('blocks', postgresql.ARRAY(sa.JSON()), nullable=True))
    op.drop_column('contents', 'data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('data', postgresql.ARRAY(postgresql.JSON(astext_type=sa.Text())), autoincrement=False, nullable=True))
    op.drop_column('contents', 'blocks')
    # ### end Alembic commands ###
