"""0005_shop_telegram_payment

Revision ID: e6e174f8a288
Revises: fe17cb54c216
Create Date: 2023-12-04 09:56:24.373721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6e174f8a288'
down_revision = 'fe17cb54c216'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_shop_telegram_payment_records', sa.Column('payment_authority', sa.String(length=128), nullable=True))
    op.add_column('credit_shop_telegram_payment_records', sa.Column('ref_id', sa.BigInteger(), nullable=True))
    op.add_column('credit_shop_telegram_payment_records', sa.Column('amount', sa.Float(), nullable=True))
    op.add_column('credit_shop_telegram_payment_records', sa.Column('currency', sa.String(length=10), nullable=False))
    op.drop_column('credit_shop_telegram_payment_records', 'image')
    op.drop_column('credit_shop_telegram_payment_records', 'reply_to_message_id')
    op.drop_column('credit_shop_telegram_payment_records', 'payment_message_id')
    op.add_column('shop_categories', sa.Column('image', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop_categories', 'image')
    op.add_column('credit_shop_telegram_payment_records', sa.Column('payment_message_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('credit_shop_telegram_payment_records', sa.Column('reply_to_message_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('credit_shop_telegram_payment_records', sa.Column('image', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('credit_shop_telegram_payment_records', 'currency')
    op.drop_column('credit_shop_telegram_payment_records', 'amount')
    op.drop_column('credit_shop_telegram_payment_records', 'ref_id')
    op.drop_column('credit_shop_telegram_payment_records', 'payment_authority')
    # ### end Alembic commands ###
