"""0020_message_nuilder

Revision ID: efedd886727d
Revises: 95e240950b26
Create Date: 2024-04-07 20:24:11.820579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efedd886727d'
down_revision = '95e240950b26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_builder_messages',
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('short_url', sa.String(length=128), nullable=True),
    sa.Column('message_text', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_builder_messages_id'), 'message_builder_messages', ['id'], unique=False)
    op.create_index(op.f('ix_message_builder_messages_short_url'), 'message_builder_messages', ['short_url'], unique=False)
    op.create_index(op.f('ix_message_builder_messages_telegram_chat_id'), 'message_builder_messages', ['telegram_chat_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_builder_messages_telegram_chat_id'), table_name='message_builder_messages')
    op.drop_index(op.f('ix_message_builder_messages_short_url'), table_name='message_builder_messages')
    op.drop_index(op.f('ix_message_builder_messages_id'), table_name='message_builder_messages')
    op.drop_table('message_builder_messages')
    # ### end Alembic commands ###
