"""nodeui and edge

Revision ID: f22fd906d11a
Revises: 641e84d700c1
Create Date: 2022-09-04 19:40:53.811052

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f22fd906d11a'
down_revision = '641e84d700c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edges',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('from_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('to_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('fromPort', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('toPort', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('chatflow_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['chatflow_id'], ['chatflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nodeuies',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('heigth', sa.Integer(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('ports', postgresql.ARRAY(sa.JSON()), nullable=True),
    sa.Column('hasDeleteAction', sa.Boolean(), nullable=True),
    sa.Column('hasEditAction', sa.Boolean(), nullable=True),
    sa.Column('chatflow_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['chatflow_id'], ['chatflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nodeuies')
    op.drop_table('edges')
    # ### end Alembic commands ###
