"""0009_product_attr

Revision ID: f2add10a328e
Revises: a9ac97a3ec03
Create Date: 2024-01-07 19:38:17.755712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2add10a328e'
down_revision = 'a9ac97a3ec03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_attributes',
    sa.Column('key', sa.String(length=255), nullable=True),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['shop_products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_attributes_id'), 'shop_attributes', ['id'], unique=False)
    op.add_column('shop_shops', sa.Column('is_info_required', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop_shops', 'is_info_required')
    op.drop_index(op.f('ix_shop_attributes_id'), table_name='shop_attributes')
    op.drop_table('shop_attributes')
    # ### end Alembic commands ###
