"""add is_active to connection chatflow

Revision ID: f46f949b010d
Revises: 605940aed2e3
Create Date: 2022-09-13 16:12:07.254737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f46f949b010d'
down_revision = '605940aed2e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connection_chatflows', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connection_chatflows', 'is_active')
    # ### end Alembic commands ###
