"""change foreign key name

Revision ID: f9ae381afaa3
Revises: 1264dd5a270f
Create Date: 2022-09-21 06:25:05.691980

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f9ae381afaa3'
down_revision = '1264dd5a270f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('parent_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.drop_constraint('categories_parrent_id_fkey', 'categories', type_='foreignkey')
    op.create_foreign_key(None, 'categories', 'categories', ['parent_id'], ['id'])
    op.drop_column('categories', 'parrent_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('parrent_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.create_foreign_key('categories_parrent_id_fkey', 'categories', 'categories', ['parrent_id'], ['id'])
    op.drop_column('categories', 'parent_id')
    # ### end Alembic commands ###
