"""0021_button_title

Revision ID: fa13035bf382
Revises: efedd886727d
Create Date: 2024-04-13 18:01:26.575987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa13035bf382'
down_revision = 'efedd886727d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_builder_messages', sa.Column('button_title', sa.String(length=255), nullable=True))
    op.drop_column('message_builder_messages', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_builder_messages', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('message_builder_messages', 'button_title')
    # ### end Alembic commands ###
