"""0015

Revision ID: faf6692de0c4
Revises: d66fb77ab811
Create Date: 2023-10-29 07:52:36.225385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faf6692de0c4'
down_revision = 'd66fb77ab811'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('credit_shop_telegram_payment_records', 'shop_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('credit_shop_telegram_payment_records', 'plan_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_index('ix_credit_shop_telegram_payment_records_plan_id', table_name='credit_shop_telegram_payment_records')
    op.drop_index('ix_credit_shop_telegram_payment_records_shop_id', table_name='credit_shop_telegram_payment_records')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_credit_shop_telegram_payment_records_shop_id', 'credit_shop_telegram_payment_records', ['shop_id'], unique=False)
    op.create_index('ix_credit_shop_telegram_payment_records_plan_id', 'credit_shop_telegram_payment_records', ['plan_id'], unique=False)
    op.alter_column('credit_shop_telegram_payment_records', 'plan_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('credit_shop_telegram_payment_records', 'shop_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
