"""payment-shipment

Revision ID: fb20a9e526bd
Revises: 4c67f9f47d98
Create Date: 2023-09-16 13:06:46.583444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb20a9e526bd'
down_revision = '4c67f9f47d98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_payment_methods',
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('shop_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shop_shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_payment_methods_id'), 'shop_payment_methods', ['id'], unique=False)
    op.create_table('shop_shipment_methods',
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('price', sa.String(length=255), nullable=True),
    sa.Column('currency', sa.String(length=255), nullable=True),
    sa.Column('shop_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shop_shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_shipment_methods_id'), 'shop_shipment_methods', ['id'], unique=False)
    op.add_column('shop_orders', sa.Column('shipment_method_id', sa.BigInteger(), nullable=True))
    op.add_column('shop_orders', sa.Column('payment_method_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'shop_orders', 'shop_shipment_methods', ['shipment_method_id'], ['id'])
    op.create_foreign_key(None, 'shop_orders', 'shop_payment_methods', ['payment_method_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shop_orders', type_='foreignkey')
    op.drop_constraint(None, 'shop_orders', type_='foreignkey')
    op.drop_column('shop_orders', 'payment_method_id')
    op.drop_column('shop_orders', 'shipment_method_id')
    op.drop_index(op.f('ix_shop_shipment_methods_id'), table_name='shop_shipment_methods')
    op.drop_table('shop_shipment_methods')
    op.drop_index(op.f('ix_shop_payment_methods_id'), table_name='shop_payment_methods')
    op.drop_table('shop_payment_methods')
    # ### end Alembic commands ###
