"""0023_embedding_cost

Revision ID: fd850bb80f29
Revises: b08fc6200530
Create Date: 2024-04-22 20:45:15.143513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd850bb80f29'
down_revision = 'b08fc6200530'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
