"""0004_is_deleted

Revision ID: fe17cb54c216
Revises: 164729a815eb
Create Date: 2023-11-09 15:33:22.190890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe17cb54c216'
down_revision = '164729a815eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_categories', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.drop_column('shop_order_items', 'product_title')
    op.add_column('shop_orders', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('shop_products', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.alter_column('shop_products', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('shop_products', 'is_available',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shop_products', 'is_available',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('shop_products', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('shop_products', 'is_deleted')
    op.drop_column('shop_orders', 'created_at')
    op.add_column('shop_order_items', sa.Column('product_title', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.drop_column('shop_categories', 'is_deleted')
    # ### end Alembic commands ###
