class WebhookType:
    CONTACT_MESSAGE = "CONTACT_MESSAGE"
    CONTACT_MESSAGE_ECHO = ("CONTACT_MESSAGE",)
    DELETE_MESSAGE = ("DELETE_MESSAGE",)
    MESSAGE_POSTBACK = "MESSAGE_POSTBACK"
    STORY_MENTION = "STORY_MENTION"
    STORY_REPLY = "STORY_REPLY"
    COMMENT = "COMMENT"
    LIVE_COMMENT = "LIVE_COMMENT"
    MESSAGE_SEEN = "MESSAGE_SEEN"
