name: Python application

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Start containers
        run: docker compose -f docker-compose-test.yaml up -d --build

      - name: Run tests
        run: docker compose -f docker-compose-test.yaml run api sh -c "./test.sh"
